title: Potato Engine API
description: Documentation for the Potato Game Engine.

theme: just-the-docs

color_scheme: dark
nav_enabled: true

baseurl: "/Potato-Engine"
url: "https://powatos.github.io/"

search:
  heading_level: 2 # limit search results to h1/h2
  preview: 1 # previews set to 1
  tokenizer_separator: '/[\s\-]+/' # keep search to title
  rel_url: false # hide url
  show_extra_fields: false # hide html

plugins:
  - jekyll-seo-tag