name: Package Engine

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build-archive:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Get latest release
        id: latest_release
        uses: actions/github-script@v7
        with:
          script: |
            const release = await github.rest.repos.getLatestRelease({
              owner: context.repo.owner,
              repo: context.repo.repo
            });

            core.setOutput("tag", release.data.tag_name);

      - name: Stage archive
        run: |
          mkdir -p staging/PotatoEngine/Source
          cp -r Source/Internal staging/PotatoEngine/Source
          cp -r Source/ThirdParty staging/PotatoEngine/Source

          cp CMakeLists.txt staging/PotatoEngine
          cp CreateMissingDefaults.cmake staging/PotatoEngine

          cp -r Data staging/PotatoEngine
          cp -r logs staging/PotatoEngine

      - name: Stage scripts
        run: |
          mkdir -p staging/scripts

          cp game.sh staging/scripts
          cp game.bat staging/scripts

      - name: Compress into archive
        run: |
          cd staging
          zip -r ../PotatoEngine.zip PotatoEngine/
        
      - name: Upload archive to release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.latest_release.outputs.tag }}
          files: PotatoEngine.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Upload scripts to release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.latest_release.outputs.tag }}
          files: staging/scripts/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}