name: Cross-Platform Build Verify

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4

      # Verify
    - name: Configure and Build (Windows)
      if: runner.os == 'Windows'
      shell: cmd
      run: |
        call game.bat conf
        call game.bat build

    - name: Configure and Build (Linux/Mac)
      if: runner.os == 'Linux' || runner.os == 'macOS'
      shell: bash
      run: |
        ./game.sh conf
        ./game.sh build